-- MySQL Script generated by MySQL Workbench
-- 12/21/16 12:12:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema srir_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema srir_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `srir_database` DEFAULT CHARACTER SET utf16 ;
USE `srir_database` ;

-- -----------------------------------------------------
-- Table `srir_database`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srir_database`.`users` (
  `iduser` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(50) NULL,
  `nick` VARCHAR(50) NULL,
  `password_hash` VARCHAR(512) NOT NULL,
  `salt` VARCHAR(512) NOT NULL,
  `email` VARCHAR(100) NULL,
  `register_date` DATETIME NULL,
  `isActive` INT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srir_database`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srir_database`.`messages` (
  `idmessage` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  PRIMARY KEY (`idmessage`),
  UNIQUE INDEX `idmessage_UNIQUE` (`idmessage` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srir_database`.`sending_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srir_database`.`sending_messages` (
  `idmessage` INT(10) UNSIGNED NOT NULL,
  `idsender` INT(10) UNSIGNED NOT NULL,
  `sending_date` DATETIME NULL,
  INDEX `idmessage_idx` (`idmessage` ASC),
  INDEX `iduser1_idx` (`idsender` ASC),
  CONSTRAINT `idmessage`
    FOREIGN KEY (`idmessage`)
    REFERENCES `srir_database`.`messages` (`idmessage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `iduser1`
    FOREIGN KEY (`idsender`)
    REFERENCES `srir_database`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
